profile:
  title: test
  description: hahaha
  themeConfig:
    heroImage: /images/uploads/8bit像素版ㄇㄚˊ幾.jpg
    disqus: ""
    nav: haha
    color:
      $accentColor: "#99B7A3"
      $secondaryColor: "#84969C"
    summary: true
    logo: /images/uploads/8bit像素版ㄇㄚˊ幾.jpg
    summaryLength: 123
    googleAnalytics: ""
    about:
      name: hhh
      image: /images/uploads/8bit像素版ㄇㄚˊ幾.jpg
      position: sss
      bio: bio
    hostname: ""
    sitemap: false
    footer: "''"
