title: 賴彥雄中醫師
description: 中醫是一種技藝而非一門學問，我的執著來自於療程中更少的疼痛與更快的療效，成為溫柔而精準的中醫師。
head:
  - - meta
    - name: viewport
      content: width=device-width,user-scalable=0,initial-scale=1.0,maximum-scale=1.0
  - - link
    - rel: stylesheet
      href: https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900
  - - link
    - rel: stylesheet
      href: https://cdn.jsdelivr.net/npm/@mdi/font@5.x/css/materialdesignicons.min.css
locales:
  /:
    lang: zh-TW
themeConfig:
  slogan: 想得多，不代表做的少
  heroImage: /images/uploads/chinesemedgo_logo.jpg
  disqus: codeshop-1
  nav:
    - text: 首頁
      link: /
      icon: 
    - text: 部落格
      link: "posts"
      icon: 
    - text: 患者評價
      link: "/#testimonial"
      icon: 
    - text: 聯絡諮詢
      link: "#contact"
      icon: 
  color:
    $accentColor: "#888988"
    $secondaryColor: "#c7cac7"
  pages: true
  summary: true
  logo: ""
  summaryLength: 100
  heroImageMask: false
  googleAnalytics: UA-122464537-1
  about:
    name: 賴彥雄醫師
    image: /images/uploads/about.jpg
    position: 中醫針灸診脈
    bio: 中醫是一種技藝而非一門學問，我的執著來自於療程中更少的疼痛與更快的療效，成為溫柔而精準的中醫師。
  hostname: https://sid.tw/
  sitemap: true
  socialMedia:
    - type: github
      link: https://github.com/sidstraw/
    - type: facebook
      link: https://facebook.com/j80304xz/
    - type: linkedin
      link: https://www.linkedin.com/in/sidstraw/
  contactUs:
    - {icon: email, title: E-mail, link: /}
    - {icon: facebook-messenger, title: FB Message, link: /}
    - {icon: line, title: Line, link: /}
    - {icon: phone, title: Phone, link: /}
  schedule: /images/uploads/S__41370852.jpg
  QRCode: /images/uploads/yk_line.png
